name: Require Version Change

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  check-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: files
        run: |
          git fetch origin ${{ github.base_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
          echo "changed=$CHANGED_FILES" >> $GITHUB_OUTPUT

      - name: Check for required file
        run: |
          echo "${{ steps.files.outputs.changed }}" | grep -q '^src/constants/version.ts$' || {
            echo "Version not modified!";
            exit 1;
          }
